# Generated by Django 5.2.3 on 2025-06-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_payslip_year_alter_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='EMP-F1AD364F'),
        ),
    ]
